// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftmkqsexkafuxxajmnzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0bWtxc2V4a2FmdXh4YWptbnpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyODcyNjAsImV4cCI6MjA1Njg2MzI2MH0.L4P5lk9o5h2_nNT-iNK4NftjlZ5JT2zdRVhuyZ4jexg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);